name: Creepers
main: com.elmakers.mine.bukkit.plugins.CreeperPlugin
version: 1.0
api-version: 1.13
website: http://mine.elmakers.com
author: TheBugWhisperer
description : A plugin to spawn creepers
commands:
  c:
    description: Spawn a bunch of creepers
    usage: c
    permission: spawncreepers
permissions:
  spawncreepers:
    description: Use the "c" command
    type: boolean
    default: op